exec-once = dbus-update-activation-environment --systemd --all
$mod=SUPER
animations {
  enabled=false
}

decoration {
  rounding=0
}

dwindle {
  no_gaps_when_only=true
  preserve_split=true
}

general {
  col.active_border=rgba(33ccffee) rgba(00ff99ee) 45deg
  col.inactive_border=rgba(595959aa)
  gaps_in=0
  gaps_out=0
  layout=dwindle
}

input {
  follow_mouse=1
  force_no_accel=true
  kb_layout=us
  kb_variant=colemak
}

xwayland {
  force_zero_scaling=true
}
bind=$mod, x, exec, com.brave.Browser
bind=$mod, RETURN, exec, alacritty
bind=$mod, q, killactive,
bind=$mod SHIFT, m, exit,
bind=$mod, c, exec, thunar
bind=$mod, j, togglesplit,
bind=$mod, s, exec, rofi -show drun -modes drun,run -show-icons
bind=$mod, z, exec, cliphist list | rofi -dmenu | cliphist decode | wl-copy
bind=$mod SHIFT, s, exec, grim -g "$(slurp)" - | swappy -f -
bind=$mod SHIFT, F11, exec, ~/.local/bin/toggle-recording.fish
bind=$mod SHIFT, F12, exec, ~/.local/bin/save-recording.fish
bind=, Print, exec, playerctl -p spotify volume 0.05-
bind=, Scroll_Lock, exec, playerctl -p spotify volume 0.05+
bind=$mod, t, fullscreen
bind=$mod, left, movefocus, l
bind=$mod, right, movefocus, r
bind=$mod, up, movefocus, u
bind=$mod, down, movefocus, d
bind=$mod, i, movefocus, r
bind=$mod, n, movefocus, l
bind=$mod, u, movefocus, u
bind=$mod, e, movefocus, d
bind=$mod SHIFT, left, movewindow, l
bind=$mod SHIFT, right, movewindow, r
bind=$mod SHIFT, up, movewindow, u
bind=$mod SHIFT, down, movewindow, d
bind=$mod SHIFT, i, movewindow, r
bind=$mod SHIFT, n, movewindow, l
bind=$mod SHIFT, u, movewindow, u
bind=$mod SHIFT, e, movewindow, d
bind=$mod, mouse_down, workspace, e+1
bind=$mod, mouse_up, workspace, e-1
bind=$mod, v, togglefloating,
bind=, XF86Launch6, exec, swaync-client -t -sw
bind=$mod, 1, workspace, 1
bind=$mod SHIFT, 1, movetoworkspace, 1
bind=$mod, 2, workspace, 2
bind=$mod SHIFT, 2, movetoworkspace, 2
bind=$mod, 3, workspace, 3
bind=$mod SHIFT, 3, movetoworkspace, 3
bind=$mod, 4, workspace, 4
bind=$mod SHIFT, 4, movetoworkspace, 4
bind=$mod, 5, workspace, 5
bind=$mod SHIFT, 5, movetoworkspace, 5
bind=$mod, 6, workspace, 6
bind=$mod SHIFT, 6, movetoworkspace, 6
bind=$mod, 7, workspace, 7
bind=$mod SHIFT, 7, movetoworkspace, 7
bind=$mod, 8, workspace, 8
bind=$mod SHIFT, 8, movetoworkspace, 8
bind=$mod, 9, workspace, 9
bind=$mod SHIFT, 9, movetoworkspace, 9
bind=$mod, 0, workspace, 10
bind=$mod SHIFT, 0, movetoworkspace, 10
bindel=, XF86AudioRaiseVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+ -l 1
bindel=, XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%- -l 1
bindl=, XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindl=, XF86AudioPlay, exec, playerctl play-pause
bindl=, XF86AudioNext, exec, playerctl next
bindl=, XF86AudioPrev, exec, playerctl previous
bindm=$mod, mouse:272, movewindow
bindm=$mod, mouse:273, resizewindow
exec-once=lxqt-policykit-agent
exec-once=waybar
exec-once=wl-paste --type text --watch cliphist store
exec-once=wl-paste --type image --watch cliphist store
exec-once=steam
exec-once=solaar -w hide
exec-once=spotify
monitor=DP-3,3840x2160@165,0x0,1.25,vrr,2
# monitor=HDMI-A-1,3840x2160@120,5000x5000,1,vrr,0
monitor=HDMI-A-1,disable
monitor=DP-1,3840x2160@60,3072x288,1.5,vrr,0
# monitor=DP-1,disable

env = LIBVA_DRIVER_NAME,nvidia
env = XDG_SESSION_TYPE,wayland
env = GBM_BACKEND,nvidia-drm
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = NVD_BACKEND,direct

workspace = 1, monitor:DP-3
workspace = 2, monitor:DP-1
workspace = 3, monitor:DP-3
workspace = 4, monitor:DP-1
workspace = 5, monitor:DP-3
workspace = 6, monitor:DP-1
workspace = 7, monitor:DP-3
workspace = 8, monitor:DP-1
workspace = 9, monitor:HDMI-A-1
